- id: doi:10.1186/s13059-018-1579-x
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs13059-018-1579-x/MediaObjects/13059_2018_1579_Fig1_HTML.png?as=webp
  extra-links:
    - type: source
      link: https://github.com/fe4960/GRIPT_BCM
      text: GRIPT source
  tags:
  - Human Genetics
  - GRIPT
  - Mendelian Disease
  - Gene Discovery
  topics:
  - 2. Human Genetics

- id: doi:10.1038/s41436-020-01003-x
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41436-020-01003-x/MediaObjects/41436_2020_1003_Fig2_HTML.png?as=webp
  extra-links:
  tags:
  - Human Genetics
  - TLCD3B
  - Retinal Dystrophy
  topics:
  - 2. Human Genetics
  
- id: doi:10.1038/s41436-020-00948-3
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41436-020-00948-3/MediaObjects/41436_2020_948_Fig3_HTML.png?as=webp
  extra-links:
    - type: source
      link: https://github.com/fe4960/Binomial_test
      text: Binomial Test source
  tags:
  - Human Genetics
  - Pathogenicity
  - Rare Variant
  - Mendelian Disease
  topics:
  - 2. Human Genetics
  
- id: doi:10.1016/j.ajhg.2017.02.008
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5384039/bin/gr2.jpg
  extra-links:
  tags:
  - Human Genetics
  - CWC27
  - Retinal Degeneration
  topics:
  - 2. Human Genetics

- id: doi:10.1016/j.ajhg.2016.10.008
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5142109/bin/gr2.jpg
  extra-links:
  tags:
  - Human Genetics
  - REEP6
  - Retinitis Pigmentosa
  - Retinal Dystrophy
  topics:
  - 2. Human Genetics
  
- id: doi:10.1186/s13059-022-02679-x
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs13059-022-02679-x/MediaObjects/13059_2022_2679_Fig1_HTML.png?as=webp
  extra-links:
    - type: preprint
      link: https://satijalab.org/seurat/v4.0/weighted_nearest_neighbor_analysis.html
      text: Dataset
    - type: source
      link: https://github.com/KChen-lab/bindSC
      text: BindSC source
  tags:
  - Single Cell Omics
  - BindSC
  - Bi-CCA
  - Integration
  topics:
  - 1. Single Cell Omics
   
- id: doi:10.1073/pnas.1901572116
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6561190/bin/pnas.1901572116fig01.jpg
  extra-links:
  tags:
  - Single Cell Omics
  - Cone and Rod Photoreceptor
  - Retinal Organoid
  topics:
  - 1. Single Cell Omics

- id: doi:10.1167/iovs.63.3.11
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8934561/bin/iovs-63-3-11-f001.jpg
  extra-links:
  tags:
  - Therapeutics
  - Tlcd3b
  - Retinal Degeneration
  - Mouse Model
  topics:
  - 3. Therapeutics

- id: doi:10.1172/JCI123980
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6355306/bin/jci-129-123980-g282.jpg
  extra-links:
  tags:
  - Therapeutics
  - Inherited Retinal Disease
  - Ophthalmology
  - Genetic Disease
  topics:
  - 3. Therapeutics

- id: doi:10.1089/hum.2018.078
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6437630/bin/fig-1.gif
  extra-links:
  tags:
  - Therapeutics
  - Retinal Degeneration
  - Retinitis Pigmentosa
  topics:
  - 3. Therapeutics

- id: doi:10.1016/j.jtos.2020.12.004
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8359589/bin/nihms-1726489-f0002.jpg
  extra-links:
  tags:
  - Single Cell Omics
  - Cornea
  - Stem Cells
  - Epithelium
  topics:
  - 1. Single Cell Omics

- id: doi:10.1038/s41467-019-12917-9
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-019-12917-9/MediaObjects/41467_2019_12917_Fig2_HTML.png?as=webp
  extra-links:
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=gse133707
      text: Dataset
  tags:
  - Single Cell Omics
  - snRNA-seq
  - Human Retina
  topics:
  - 1. Single Cell Omics

- id: doi:10.1016/j.xgen.2023.100298
  image: https://www.cell.com/cms/attachment/515d02fa-99ad-4048-bb86-e8cf7d257107/gr1.jpg
  extra-links:
    - link: https://cellxgene.cziscience.com/collections/af893e86-8e9f-41f1-a474-ef05359b1fb7
      text: Data visualization
  tags:
  - Multi-omics atlas
  - scRNA-seq
  - Human Retina
  topics:
  - 1. Single Cell Omics

- id: doi:10.1186/s13059-023-03111-8
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs13059-023-03111-8/MediaObjects/13059_2023_3111_Fig1_HTML.png?as=webp
  extra-links:
  tags:
  - sc-eQTL
  - sc-caQTL
  - sc-ASCA
  - sc-ASE
  - Single cell multiomics
  topics:
  - 1. Single Cell Omics

- id: doi:10.1038/s41467-023-40674-3
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-023-40674-3/MediaObjects/41467_2023_40674_Fig1_HTML.png?as=webp
  extra-links:
    - link: https://cellatlas.research.bcm.edu/
      text: Data visualization
  tags:
  - Spatial
  - Mouse Retina
  - MERFISH
  topics:
  - 1. Single Cell Omics

- id: doi:10.1038/s41467-024-50853-5
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-024-50853-5/MediaObjects/41467_2024_50853_Fig1_HTML.png?as=webp
  extra-links:
    - link: https://cellxgene.cziscience.com/collections/4832df54-d357-4d0f-b601-e924823b38b7
      text: Data visualization
  tags:
  - Developing
  - Human Retina
  - Single cell multiomics
  topics:
  - 1. Single Cell Omics

- id: doi:10.1038/s41596-025-01220-1
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41596-025-01220-1/MediaObjects/41596_2025_1220_Fig1_HTML.png?as=webp
  extra-links:
    - type: source
      link: https://github.com/RCHENLAB/scGPT_fineTune_protocol
      text: scGPT finetune protocol
  tags:
  - Foundation model finetuning
  - Protocol
  - Single cell multiomics
  topics:
  - 1. Single Cell Omics

- id: doi:10.1101/gr.279167.124
  image: https://genome.cshlp.org/content/35/4/740/F1.large.jpg
  extra-links:
    - link: https://genome.ucsc.edu/s/wmeng1018/Mouse_retina_transcript_isoform_by_LR
      text: Data visualization
  tags:
  - Long-read sequencing
  - Mouse Retina
  - Single cell multiomics
  - Transcription isoform
  topics:
  - 1. Single Cell Omics

- id: doi:10.1038/s41597-025-04528-5
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41597-025-04528-5/MediaObjects/41597_2025_4528_Fig1_HTML.png?as=webp
  extra-links:
  tags:
  - Trabecular meshwork (TM)
  - Glaucoma
  - Single cell multiomics
  topics:
  - 1. Single Cell Omics

- id: doi:10.1101/gr.278822.123
  image: https://genome.cshlp.org/content/35/1/147/F1.large.jpg
  extra-links:
    - type: source
      link: https://github.com/wwylab/DeMixSC
      text: DeMixSC source
  tags:
  - Cell-type deconvolution
  - Single cell multiomics
  topics:
  - 1. Single Cell Omics

- id: doi:10.1136/jmg-2025-110681
  image: https://jmg.bmj.com/content/jmedgenet/62/11/693/F1.large.jpg
  extra-links:
  tags:
  - Human Genetics
  - Mendelian Disease
  - Novel Gene Discovery
  topics:
  - 2. Human Genetics
